describe('Register User', () => {
    it('should register a new user', () => {
        cy.visit('https://automationexercise.com')
        cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
        cy.get('.signup-form > form > [type="text"]').type('Andrea')
        cy.get('.signup-form > form > [type="email"]').type('tteesstt@example.com')
        cy.get('.signup-form > form > [type="submit"]').click()
        cy.get('#id_gender1').check()
        cy.get('#password').type('password')
        cy.get('#days').select('1')
        cy.get('#months').select('January')
        cy.get('#years').select('2003')
        cy.get('#newsletter').check()
        cy.get('#optin').check()
        cy.get('#first_name').type('John')
        cy.get('#last_name').type('Doe')
        cy.get('#company').type('My Company')
        cy.get('#address1').type('1234 Street')
        cy.get('#address2').type('Unit 101')
        cy.get('#country').select('Canada')
        cy.get('#state').type('Ontario')
        cy.get('#city').type('Toronto')
        cy.get('#zipcode').type('12345')
        cy.get('#mobile_number').type('1234567890')
        cy.get('.signup-form > form > [type="submit"]').click()
        cy.get('.alert-success').should('contain', 'Signup successful')
    })
})
describe('Login User', () => {
    it('should login an existing user', () => {
        cy.visit('https://automationexercise.com')
        cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
        cy.get('.login-form > form > [type="email"]').type('john.doe@example.com')
        cy.get('.login-form > form > [type="password"]').type('password')
        cy.get('.login-form > form > [type="submit"]').click()
        cy.get('.shop-menu > .nav > :nth-child(4) > a').should('contain', 'Logout')
    })
})
describe('Add Product to Cart', () => {
    it('should add a product to the cart', () => {
        cy.visit('https://automationexercise.com')
        cy.get(':nth-child(2) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('.product-information > .cart > .btn').click()
        cy.get('.modal-body').should('contain', 'Product added')
    })
})
describe('Place Order and Checkout', () => {
    it('should place an order and checkout', () => {
        cy.visit('https://automationexercise.com')
        cy.get(':nth-child(2) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('.product-information > .cart > .btn').click()
        cy.get('.modal-footer > .btn').click()
        cy.get(':nth-child(2) > :nth-child(2) > .cart_quantity_up').click()
        cy.get('.cart_navigation > .btn').click()
        cy.get('.cart_navigation > .btn').click()
        cy.get('.cheque-indent > .dark').should('contain', 'Your order on My Store is complete.')
    })
})
describe('Download Invoice', () => {
    it('should allow a user to download invoice', () => {
        cy.visit('https://automationexercise.com')
        cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
        cy.get('.login-form > form > [type="email"]').type('tteest@example.com')
        cy.get('.login-form > form > [type="password"]').type('pwd')
        cy.get('.login-form > form > [type="submit"]').click()
        cy.get(':nth-child(5) > a').click()
        cy.get('.btn').click()
        cy.url().should('include', 'invoice-download')
    })
})
